# Generated by Django 2.0.1 on 2020-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='知识卡片模板名称')),
                ('content', models.CharField(max_length=5000, null=True, verbose_name='知识卡片模板内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.TextField(null=True, verbose_name='节点')),
                ('record', models.TextField(null=True, verbose_name='记录')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '历史操作表',
                'verbose_name_plural': '历史操作表',
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Knowledge_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='需求百科名称')),
                ('content', models.TextField(verbose_name='知识卡片内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Noumenon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noumenon_name', models.TextField(null=True, verbose_name='本体名称')),
                ('noumenon_attribute', models.TextField(null=True, verbose_name='本体属性')),
            ],
            options={
                'verbose_name': '本体表',
                'verbose_name_plural': '本体表',
                'db_table': 'noumenon',
            },
        ),
        migrations.CreateModel(
            name='Require_wikipedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='需求百科名称')),
                ('content', models.TextField(verbose_name='需求百科内容')),
                ('Knowledge_card', models.CharField(max_length=50, null=True, verbose_name='知识卡片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Wikipedia_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='模板名称')),
                ('content', models.CharField(max_length=5000, verbose_name='模板内容')),
                ('card_template', models.CharField(max_length=256, null=True, verbose_name='知识卡片模板内容')),
            ],
        ),
    ]
