# Generated by Django 2.1.11 on 2020-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='知识卡片模板名称')),
                ('content', models.CharField(max_length=5000, null=True, verbose_name='知识卡片模板内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='需求百科名称')),
                ('content', models.TextField(verbose_name='知识卡片内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Require_wikipedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='需求百科名称')),
                ('content', models.TextField(verbose_name='需求百科内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Wikipedia_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='模板名称')),
                ('content', models.CharField(max_length=5000, verbose_name='模板内容')),
                ('card_template', models.CharField(max_length=256, null=True, verbose_name='知识卡片模板内容')),
            ],
        ),
    ]
