# Generated by Django 2.0.1 on 2020-10-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='require_wikipedia',
            old_name='Knowledge_card',
            new_name='knowledge_card',
        ),
    ]
