# Generated by Django 2.0.1 on 2020-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0003_histogram_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histogram',
            name='time',
            field=models.IntegerField(verbose_name='时间'),
        ),
    ]
