# Generated by Django 2.0.1 on 2020-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0004_auto_20201023_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histogram',
            name='time',
            field=models.CharField(max_length=100, verbose_name='时间'),
        ),
    ]
