# Generated by Django 2.0.1 on 2020-10-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0007_data_mining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_mining',
            name='status',
        ),
        migrations.AddField(
            model_name='data_mining',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='模型名称'),
        ),
    ]
