# Generated by Django 2.0.1 on 2020-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0008_auto_20201024_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge_reasoning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('start_node_uuid', models.CharField(max_length=100, verbose_name='开始节点')),
                ('relation_type', models.CharField(max_length=100, verbose_name='关系类型')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('creat_time', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='histogram',
            name='project_id',
            field=models.CharField(max_length=100, null=True, verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='project_id',
            field=models.CharField(max_length=100, null=True, verbose_name='项目id'),
        ),
    ]
