# Generated by Django 2.0.1 on 2020-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_code_manage', '0009_auto_20201026_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation_analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('start_node_uuid', models.CharField(max_length=100, verbose_name='开始节点')),
                ('end_node_uuid', models.CharField(max_length=100, verbose_name='终止节点')),
            ],
        ),
    ]
